---
title: "Compare mosaic variants"
output:
  html_document:
    df_print: paged
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r initialize, echo=FALSE, message=FALSE, warning=FALSE}
library("patchwork")
library("gridExtra")
library("sf")
library("tidyverse")

tidy_dir <- 'data/tidy'
code <- 'HV_nu'
# suffix <- 'cappt2_conserv13'
year <- '2019'
palsar_dir <- file.path(tidy_dir, str_c('palsar_', year))
modeling_dir <- file.path('data/modeling', code)

var_order <- c('simple', 'cappt2_conserv13', 'cappt2_conserv13_mean5', 'med5', 'lee11s10', 'maskLU_lee11s10_LCinterp')
```

## Percent of land pertaining to PALSAR masks

```{r PALSAR mask, eval =  TRUE, echo=FALSE, message=FALSE, fig.width=7, fig.height=3}
# ~Look~ at proportion of values in each mask category----
report_fp <- file.path('data', 'reports', str_glue('palsar{year}_mask_pcts.csv'))
if(!file.exists(report_fp)) {
  
  # Load PALSAR mask
  msk_fp <- file.path(palsar_dir, str_glue('mask{suffix}.tif'))
  dn_mask <- terra::rast(msk_fp)
  
  # Get values
  rvals <- terra::values(dn_mask)
  
  # Count pixels in each category and convert to percentage
  df <- tibble(group = c("Normal", "Layover", "Shadowing"), 
               count = c(sum(rvals == 255, na.rm=TRUE), 
                         sum(rvals == 100, na.rm=TRUE),
                         sum(rvals == 150, na.rm=TRUE)))
  
  # Convert counts to percentage of all land pixels
  landct <- sum(df$count)
  df <- df %>%
    dplyr::add_row(group = 'Land', count = landct) %>% 
    dplyr::mutate(pct = count / landct)
  
  # Save as CSV
  df %>% write_csv(report_fp)
}

# Read DF
df <- read_csv(report_fp)

# Pie chart
bp <- ggplot(filter(df, group %in% c('Normal', 'Shadowing', 'Layover')),
              aes(x="", y=pct, fill=group, name = 'Mask')) +
    geom_bar(width = 1, stat = "identity") +
    theme_minimal() + 
  labs(fill="Mask",x=NULL,y=NULL,title="",caption="") +
  theme(axis.line = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        panel.grid = element_blank()) +
  coord_polar("y", start=0)

# Table
d2 <- df %>% 
  mutate(percent = str_c(round(pct*100, digits = 1), '%')) %>% 
  arrange(desc(pct)) %>% 
  select(group, percent) %>% 
  filter(group != 'Land')

tab <- gridExtra::tableGrob(d2, rows = NULL, cols = c('Mask', 'Percent of land'))

# Display side-by-side
wrap_plots(tab, bp)
```

## Compare regressions with different filters
### Scatterplots

```{r facetted scatterplots, eval=TRUE, echo=FALSE, fig.height=6, fig.width=8, message=FALSE}
load_plot_vals <- function(fp) {
  # Get variant code
  items <- str_split(dirname(fp), '/')
  g0_variant <- suffix <- nth(items[[1]], -2)
  
  # Load data
  g0_agb <- read_csv(fp) %>% 
    dplyr::select(AGB = AGB_ha, backscatter = g0_mean) %>% 
    mutate(AGB = as.numeric(AGB),
           g0_variant = g0_variant) 
}

fps <- list.files(modeling_dir,
                  pattern = "^plots_agb_g0.*\\.csv",
                  recursive = TRUE, 
                  full.names = TRUE)


vals <- fps %>% 
  map_dfr(load_plot_vals) %>% 
  mutate(g0_variant = factor(g0_variant, levels = var_order))

# Scatterplot - AGB against backscatter
p <- ggplot(vals, aes(x=backscatter, y=AGB)) +
    geom_point(size=0.5) +
  labs(y = expression(paste("Aboveground biomass (Mg ha"^"-1", ")")),
       x = expression(paste("Radar backscatter, ",sigma['HV']^0))) + # ," (m"^2, "/m"^2, ")"
  geom_smooth(method='lm', 
              se=TRUE, 
              fullrange=TRUE, 
              level=0.95, 
              col='black', 
              size=0.2) +
  facet_wrap(facets=vars(g0_variant)) +
  coord_fixed(ratio = .0005) +
  theme(strip.background = element_blank(),
        strip.text = element_text(hjust=0))

# Save
ggsave(file.path('figures', year, 'modeling', str_glue('compare_scatter_agb_g0.png')),
       width=19, height=12, units='cm')

p
```

### Test statistics
We want to see high correlation (adjusted R2) and low Bias, RMSE, and MAE. 

```{r model summaries table, eval=TRUE, echo=FALSE, message=FALSE, fig.height=3, fig.width=5}
summarize_results <- function(full_results_csv, digits = 3) {
  
  # Get variant code
  g0_variant <- suffix <-  full_results_csv %>% 
    str_extract(str_glue('(?<={code}/).*(?=/cal)'))
  suffix <- if(suffix == 'simple') '' else str_c('_', suffix)
  
  # Inset table with regression summary
  full_results <- read_csv(full_results_csv)
  
  # Values from model training
  d1 <- full_results %>% 
    filter(type == 'train') %>%
    pivot_wider() %>% 
    dplyr::select(Intercept = estimate_int, 
                  Slope = estimate_g0, 
                  P = p.value)
  
  # Values from model testing (repeated k-fold cross-validation)
  d2 <- full_results %>% 
    filter(type == 'test') %>%
    pivot_wider() %>% 
    dplyr::select(Adj_R2 = adj.r.squared, 
                  Adj_R2_sd = adj.r.squaredSD, 
                  RMSE, 
                  RMSE_SD = RMSESD, 
                  MAE,
                  MAE_SD = MAESD, 
                  Bias, 
                  Bias_SD = BiasSD)
  
  # Combine into one table
  report_tbl <- bind_cols(d1, d2) %>% 
    mutate(across(everything(), ~ signif(.x, digits)), 
           Filter = g0_variant)
}

# Read model results as list of tibbles
fps <- list.files(modeling_dir, 'model_results_.*\\.csv', 
                  recursive = TRUE, 
                  full.names = TRUE)
variants <- fps %>% str_extract(str_glue('(?<={code}/).*(?=/cal)'))
out <- fps %>% map(read_csv)

# Format
out2 <- out %>% 
  map_dfr(pivot_wider, names_from = c(name, type)) %>% 
  select(Intercept = estimate_int_train, 
                Slope = estimate_g0_train, 
                Intcpt_95CI = ci_int_train, 
                Slope_95CI = ci_slope_train,
                Adj_r2 = adj.r.squared_train, 
                starts_with('rmse'), 
                starts_with('mae'),
                starts_with('Bias')
                ) %>% 
  mutate(across(where(is.numeric), ~ signif(.x, digits = 4))) %>% 
  bind_cols(tibble(Variant = variants), .)

# Save
report_fp <- file.path('data/reports', str_c('model_results_by_variant_', code, '.csv'))
out2 %>% write_csv(report_fp)

# Alternative version that I set up to make graphics
fps <- list.files(modeling_dir,
                  pattern = "^model_results.*\\.csv",
                  recursive = TRUE, 
                  full.names = TRUE)

results_sum <- fps %>% map_dfr(summarize_results, digits = 3)
results_summary <- results_sum %>% 
  arrange(factor(Filter, 
                 levels = c('simple', 'cap7k_conserv13', 'agg50', 'lee11s10',
                            'med5', 'cap7k_med5'))
          ) %>% 
  dplyr::select(-P) %>% 
  column_to_rownames('Filter') %>% 
  dplyr::select(-ends_with('_sd')) 

tab <- gridExtra::tableGrob(results_summary, 
                            theme = ttheme_default(base_size = 11)) 
# patchwork::wrap_elements(tab)
```
```{r model summaries graphs, echo=FALSE, message=FALSE, fig.height=3.5, fig.width=4}
# Reformat results table for plotting

# Prep
rs1 <- results_sum %>% 
  mutate(g0_variant = factor(Filter, levels = var_order)) %>% 
    dplyr::select(starts_with('adj_r2'), 
                  starts_with('rmse'), 
                  starts_with('mae'), 
                  starts_with('bias'),
                  g0_variant)

# Format values
rs2a <- rs1 %>% 
  dplyr::select(-ends_with('sd')) %>% 
  pivot_longer(c(-g0_variant, -ends_with('sd'))) 

# Format value SDs
rs2b <- rs1 %>% 
  dplyr::select(c(g0_variant, ends_with('sd'))) %>% 
  pivot_longer(-g0_variant, values_to = 'sd') %>% 
  mutate(name = str_remove_all(name, regex('_sd', ignore_case = TRUE)))

# Join values and SDs
res_sum <- left_join(rs2a, rs2b)

# Plot
pt_plot <- ggplot(res_sum, aes(x=g0_variant, y=value)) +
  geom_line(aes(group = name), show.legend = FALSE) +
  geom_point(aes(group = name), show.legend = FALSE) +
  geom_errorbar(aes(ymin=value-sd, ymax=value+sd), width=.2, show.legend = FALSE) +
  scale_y_continuous(n.breaks =  3, sec.axis = dup_axis(breaks=scales::extended_breaks(n = 3))) +
  facet_wrap(facets=vars(name), ncol=1, scales = 'free_y', strip.position = 'left') +
  theme(axis.title = element_blank(), 
        axis.text.x = element_text(angle = 45, hjust=1),
        axis.text.y.left = element_blank(),
        axis.ticks.y.left = element_blank(),
        strip.text.y.left = element_text(angle = 0),
        strip.background = element_blank(),
        panel.grid.minor = element_blank(),
        plot.margin = unit(c(1,1,1,1), c('mm','mm','mm','mm')),
        plot.title.position = 'plot') +
  ggtitle('Model testing results')
# pt_plot
```
```{r display summaries, echo=FALSE, fig.height=5, fig.width=10, message=FALSE}
layout <- c(
  area(t = 1, l = 1, b = 5, r = 2),
  area(t = 1, l = 2.5, b = 5, r = 10)
)

# Combine plot and table
wrap_plots(list(pt_plot, tab), ncol=2) +
  plot_layout(design = layout)
```

```{r save plots, echo=FALSE, fig.height=6, fig.width=12, message=FALSE, include=FALSE}
# Combine plot and table
wrap_plots(list(p, pt_plot), nrow=1) + plot_layout(widths = c(4,1))

# Save
ggsave(file.path('figures', year, 'modeling', str_glue('compare_scatter_and_graphs.png')),
       width=10.5, height=6, units='in')
```

There is no significant difference in performance statistics between filtering options so we'll use 5x5 median as the most conceptually simple de-noising option. 

```{r show final choice, echo=FALSE, fig.height=2, fig.width=7, message=FALSE}
g0_variant <- 'med5'
final_vals <- results_sum %>% filter(Filter == g0_variant)

d1 <- final_vals %>% 
  transmute(
    P = {if(P < 0.001) '< 0.001' else if(P < 0.05) '< 0.05' else '>= 0.05'},
    Equation = str_glue("AGB = {Intercept} + {Slope}x")) %>% 
  dplyr::select(Equation, P) %>%
  pivot_longer(everything()) %>%
  column_to_rownames('name')

d2 <- final_vals %>% 
  transmute(
    Adj_R2 = str_c(format(Adj_R2, digits = 2), " ± ", 
                           format(Adj_R2_sd, digits = 2)),
    RMSE = str_c(format(RMSE, digits = 3), " ± ", format(RMSE_SD, digits = 2)),
    MAE = str_c(format(MAE, digits = 3), " ± ", format(MAE_SD, digits = 2)),
    Bias = str_c(format(Bias, digits = 3), " ± ", format(Bias_SD, digits = 2)))  %>%
  pivot_longer(everything()) %>%
  column_to_rownames('name')

# d3 <- bind_rows(d1, d2)

tab1 <- gridExtra::tableGrob(d1, 
                             cols = NULL) 

tab2 <- gridExtra::tableGrob(d2, 
                             cols = NULL) 

wrap_plots(list(tab1, tab2), ncol=2) +
  plot_annotation(title = g0_variant)
```